version: '3'
# base docker config
services:
  db:
    container_name: backend-db
    image: postgres:14.5-bullseye
    env_file:
      - .env
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - decentdisk
  be:
    container_name: backend-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - ipfs
    env_file:
      - .env
    working_dir: '/app'
    restart: on-failure
    volumes:
      - './:/app'
    networks:
      - decentdisk
  ipfs:
    container_name: backend-ipfs
    image: ipfs/kubo:latest
    env_file:
      - .env
    volumes:
      - ${IPFS_STAGING}:/export
      - ${IPFS_DATA}:/data/ipfs
    networks:
      - decentdisk
  node:
    container_name: backend-node
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    working_dir: '/app'
    volumes:
      - './:/app'
    networks:
      - decentdisk
networks:
  decentdisk:
    external: true