version: '3'
# base docker config
services:
  db:
    image: postgres:14.5-bullseye
    env_file:
      - .env
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    restart: on-failure
  be:
    image: node:18.14.2-slim
    depends_on:
      - db
      - ipfs
    env_file:
      - .env
    working_dir: '/app'
    restart: on-failure
    volumes:
      - './:/app'
  ipfs:
    image: ipfs/kubo:latest
    env_file:
      - .env
    volumes:
      - ${IPFS_STAGING}:/export
      - ${IPFS_DATA}:/data/ipfs
  node:
    image: node:18.14.2-slim
    env_file:
      - .env
    working_dir: '/app'
    volumes:
      - './:/app'
