version: '3'
services:
  db:
    hostname: "${POSTGRES_HOST}"
    image: postgres:14.5-bullseye
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    restart: on-failure
  be:
    image: node:18.14.2-slim
    depends_on:
      - db
      - ipfs
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    command: >      
      bash -c "npm run start:dev"
    working_dir: '/app'
    restart: on-failure
    volumes:
      - './:/app'
  ipfs:
    image: ipfs/kubo:latest
    env_file:
      - .env
    volumes:
      - ${IPFS_STAGING}:/export
      - ${IPFS_DATA}:/data/ipfs
    ports:
      - "${P2P_PORT}:4001"
      - "${P2P_PORT}:4001/udp"
      - "${GATEWAY_PORT}:8080"
      - "${RPC_API}:5001"